### ISSUE TITLE
CSS_

### ISSUE THREAD

**Issue by tsuifei** [tsuifei/blogs#17]
第一期 Lesson 2-2 之 CSS

### pseudo class(:hover, :first-child, :nth-child)
可選某個狀態的樣子

### pseudo element(::before, ::after)
可以選到不存在的元素
第一種寫法
```css
.box::before {
	content:'hi';
}
```
第二種寫法，利用attr()
```css
.box::before {
	content: attr(data-index)
}
```
在html裡加入特定標籤，記得自己加的html屬性前要加data，和原生的屬性做區別。
```html
<div class='box' data-index='1'>box1</div>
<div class='box' data-index='2'>box2</div>
```

### css selector + ~
拿來排版很好用
div + ul
div + ul
```css
.first + .box {
         // 選.first 後面的.box
}
.first ~ .box {
         // 選.first同一階層的所有.box
}
.box + .box {
         // 選.first除了第一個以外的.box
}
```
```html
div class="first">first</div>
<div class='box' data-index='1'>box1</div>
```

### transition
漸變動畫
```css
.box {
	width:200px;
	height:200px;
	background: red;
	transition: all 0.3s ease-in
	// 對哪個元素監控 / 時間 /特效
	}
.box:hover {
	background: orange;
}
```
### transform
對元素做一些變形效果
transform: scale(1.2) 放大1.2倍
transform: translateX(10px) X,Y軸移動
transform: rotate(10deg) 斜轉

### css prefix 
前綴，依瀏覽器不停而衍生的語法
-o-transition 針對opera
-ms-transition 針對ie
-moz-transition 針對mozila
-webkit-transition 針對 chrome safari
查詢是否需要加prefix網站：shouldiprefix.com

### css naming
當元素越來越多，CSS需要有規則的命名方法
BEM(Block Element Modifier)
block__element--modifier
以一個區塊為單位，單位裡的細部內容名稱以雙底線分隔，如post__info

#### inline
元素一但設定為inline，元素設定的寬高就會無效
padding 左右有作用，但上下無作用
margin也一樣 左右有作用，但上下無作用
如果加了border 元素不會動，但border會撐開
#### bloc 
一個元素佔一行
#### inline-bloc 
同樣像inline可以並排
並排時的小陷阱：如果把margin刪掉，元素間仍然有空白，是因為在html裡面是一個元素一行，只要把html的元素都並排成一行即可解決。或加html的註解，

### 將margin包含在block的方法，使用box-sizing
```css
box-sizing: content-box; /*為預設值*/
box-sizing: border-box; /*把border包在盒子裡，如果有margin也會往border裡擠*/
```
### reset.css 和 normalize.css
reset.css 把所有個瀏覽器的預設樣式都清空，讓我們寫的樣式在個瀏覽器上一致
normalize.css 正規化。與其把個瀏覽器的預設樣式清空，不如調整每個瀏覽器的預設為一致
